name: Update Wiki on Demand

on:
  workflow_dispatch:
    inputs:
      user_id:
        type: string
        description: 'Enter the User ID'
        required: true
      numer_id:
        type: string
        description: 'Enter the Numer ID'
        required: true

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Wiki Repository
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN }}
        run: |
          git config --global user.email "michal.solarek@outlook.com"
          git config --global user.name "Michal Solarek"
          git clone https://x-access-token:$API_TOKEN_GITHUB@github.com/solarekm/test_repo.wiki.git

      - name: Get Current Date
        id: current-date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update Wiki File
        env:
          USER_ID: ${{ github.event.inputs.user_id }}
          NUMER_ID: ${{ github.event.inputs.numer_id }}
        run: |
          NEW_ENTRY="| ${{ github.event.inputs.user_id }} | $CURRENT_DATE | ${{ github.event.inputs.numer_id }} | ${{ github.actor }} |"
          WIKI_FILE="test_repo.wiki/wiki-update.md"
          if [[ ! -f "$WIKI_FILE" ]]; then
            echo -e "## Workflow Log\n\n" > "$WIKI_FILE"
            echo -e "| User ID | Date | Numer ID | GitHub Actor |\n| --- | --- | --- | --- |\n" >> "$WIKI_FILE"
          fi
          sed -i "3i$NEW_ENTRY" "$WIKI_FILE"      

      - name: Commit and Push Changes to Wiki
        run: |
          cd test_repo.wiki
          git add .
          git commit -m "Update Wiki"
          git push
