name: Update Wiki
      
on:
  workflow_dispatch:
    inputs:
      destinationHubEnv:
        description: Select destination hubEnv
        required: true
        type: choice
        options:
          - 'EMEA_TEST'
          - 'EMEA_INT'
          - 'EMEA_E2E'
          - 'EMEA_PROD'
          - 'US_E2E'
          - 'US_PROD'
          - 'CN_E2E'
          - 'CN_PROD'
      currentVersion:
            type: string
            description: 'Enter the Current Version'
            required: true
      previousVersion:
              type: string
              description: 'Enter the Previous Version'
              required: true
      crqNumber:
        type: string
        description: 'Enter the CRQ number'
        required: true

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    env: 
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN }}
      HUB_ENV: ${{github.event.inputs.destinationHubEnv}}
      CURRENT_VERSION: ${{github.event.inputs.currentVersion}}
      PREVIOUS_VERSION: ${{github.event.inputs.previousVersion}}
      USER: ${{github.actor }}
      CRQ: ${{ github.event.inputs.crqNumber }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Wiki Repository
        run: |
          git config --global user.email "michal.solarek@outlook.com"
          git config --global user.name "Michal Solarek"
          git clone https://x-access-token:${{ env.API_TOKEN_GITHUB }}@github.com/solarekm/test_repo.wiki.git

      - name: Get Current Date
        id: current-date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update Wiki File
        run: |
          # Nazwa pliku Markdown
          FILE="test_repo.wiki/Home.md"

          # Funkcja do dodawania danych do tabeli dla wybranego HUB_STAGE
          update_table() {
              local hub_stage="${{ env.HUB_ENV }}"
              local current_version="${{ env.CURRENT_VERSION }}"
              local previous_version="${{ env.PREVIOUS_VERSION }}"
              local tmp_file=$(mktemp)

              # Komenda sed, która znajdzie linię z hub_stage i zaktualizuje odpowiednie kolumny
              sed "/^| $hub_stage /{s/| [^ |]* | [^ |]* |$/| $current_version | $previous_version |/}" $FILE > "$tmp_file" && mv "$tmp_file" $FILE
          }
          # Funkcja do dodawania danych do historii wdrożeń
          update_history() {
              local tmp_file=$(mktemp)

              # Dodaj nowy wiersz bezpośrednio po linii separatora tabeli
              sed "/|------|---------|---------|-----|------|---------|/a| $(date +'%Y-%m-%d %H:%M:%S') | $HUB_ENV | $CURRENT_VERSION | $CRQ | $USER | |" $FILE > "$tmp_file" && mv "$tmp_file" $FILE
          }

          # Sprawdzenie, czy plik istnieje i inicjalizacja nagłówków, jeśli to konieczne
          if [ ! -f "$FILE" ]; then
              echo "## Deployed Versions" > $FILE
              echo "| Hub_Stage | Current version | Previous version |" >> $FILE
              echo "|------------|-------------------|--------------------|" >> $FILE
              echo "| EMEA_E2E   | \$current_version | \$previous_version |" >> $FILE
              echo "| EMEA_PROD  | \$current_version | \$previous_version |" >> $FILE
              echo "| US_E2E     | \$current_version | \$previous_version |" >> $FILE
              echo "| US_PROD    | \$current_version | \$previous_version |" >> $FILE
              echo "| CN_E2E     | \$current_version | \$previous_version |" >> $FILE
              echo "| CN_PROD    | \$current_version | \$previous_version |" >> $FILE

              echo "## Deployment History" >> $FILE
              echo "| DATA | HUB_ENV | TAG_SHA | CRQ | USER | COMMENT |" >> $FILE
              echo "|------|---------|---------|-----|------|---------|" >> $FILE
          fi

          # Zaktualizuj tabelę dla wybranej opcji
          update_table "$hub_stage" "$current_version" "$previous_version"
          # Zaktualizuj historię wdrożeń
          update_history
          
      - name: Commit and Push Changes to Wiki
        run: |
          cd test_repo.wiki
          git add .
          git commit -m "Update Wiki"
          git push