name: Update Wiki on Demand

on:
  workflow_dispatch:
    inputs:
      crq_id:
        type: string
        description: 'Enter the CRQ ID'
        required: true
      numer_id:
        type: string
        description: 'Enter the Numer ID'
        required: true

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Wiki Repository
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN }}
        run: |
          git config --global user.email "michal.solarek@outlook.com"
          git config --global user.name "Michal Solarek"
          git clone https://x-access-token:$API_TOKEN_GITHUB@github.com/solarekm/test_repo.wiki.git

      - name: Get Current Date
        id: current-date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update Wiki File
        env:
          numer_crq: ${{ github.event.inputs.crq_id }}
          NUMER_ID: ${{ github.event.inputs.numer_id }}
          uzytkwnik: ${{ github.actor }}
        run: |
          # Nazwa pliku Markdown
          FILE="test_repo.wiki/Home.md"

          # Sprawdzenie, czy plik istnieje
          if [ ! -f "$FILE" ]; then
              # Tworzenie nagłówków tabeli, jeśli plik nie istnieje
              echo "| Data | Użytkownik | Aktualny obraz | Poprzedni obraz | Numer CRQ | Komentarz |" > $FILE
              echo "|------|------------|----------------|----------------|-----------|-----------|" >> $FILE
          fi

          # Zapisanie nowego wiersza pod nagłówkami
          sed -i "3i| $CURRENT_DATE | $uzytkownik | $aktualny_obraz | $poprzedni_obraz | $numer_crq | $komentarz |" $FILE

      - name: Commit and Push Changes to Wiki
        run: |
          cd test_repo.wiki
          git add .
          git commit -m "Update Wiki"
          git push
