name: Update Wiki on Demand

on:
  workflow_dispatch:
    inputs:
      user_id:
        type: string
        description: 'Enter the User ID'
        required: true
      numer_id:
        type: string
        description: 'Enter the Numer ID'
        required: true

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Wiki Repository
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN }}
        run: |
          git config --global user.email "michal.solarek@outlook.com"
          git config --global user.name "Michal Solarek"
          git clone https://x-access-token:$API_TOKEN_GITHUB@github.com/solarekm/test_repo.wiki.git

      - name: Update Wiki File
        env:
          USER_ID: ${{ github.event.inputs.user_id }}
          NUMER_ID: ${{ github.event.inputs.numer_id }}
          CURRENT_DATE: ${{ env.CURRENT_DATE }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          python update_wiki.py
        id: update-wiki

      - name: Set Current Date
        id: current-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"


      - name: Commit and Push Changes to Wiki
        run: |
          cd test_repo.wiki
          git add .
          git commit -m "Update Wiki"
          git push
